# Generated by Django 5.1.3 on 2024-11-26 14:15

import mail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_email_attachment_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachment',
            name='file',
            field=models.FileField(upload_to=mail.models.get_attachment_path),
        ),
    ]
