# Generated by Django 5.1.3 on 2024-11-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_emailattachment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='email',
            name='user',
        ),
    ]
