# Generated by Django 5.1.3 on 2024-11-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_remove_email_attachment_remove_email_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['timestamp'], name='mail_email_timesta_0f6349_idx'),
        ),
        migrations.AddConstraint(
            model_name='email',
            constraint=models.UniqueConstraint(fields=('sender', 'subject', 'body', 'timestamp'), name='unique_email_within_minute'),
        ),
    ]
